_dev:
    - !C.project
        name : "pylon-ng"
        root : "./"
    - !C.version
        file : "src/version.txt"
    - !C.git
        remote : "git@github.com:xcodecraft/pylon-ng.git"
    - !C.sonar
        runner   : "/data/x/tools/sonar/bin/sonar-runner"
        qube     : "http://sonar.ayibang.cn"
        src      : "src/pylon"
        test     : "test/pylon"
        language : "php"
        config:
            - "sonar.php.coverage.reportPath=test/pylon/reports/phpunit.coverage.xml"
            - "sonar.php.tests.reportPath=test/pylon/reports/phpunit.report.xml"
