_dev:
    - !C.project
        name : "pylon-ng"
        root : "${HOME}/devspace/pylon-ng"
    - !C.version
        file : "src/version.txt"
    - !C.git
        remote : "git@github.com:xcodecraft/pylon-ng.git"
    - !C.sonar
        runner   : "/data/x/tools/sonar/bin/sonar-runner"
        qube     : "http://sonar.ayibang.cn"
        src      : "src"
        language : "php"
